### ISSUE TITLE
Handler of active page is called two times on backend rebuild

### ISSUE THREAD

**Issue by apopant** [interval/interval-node#17] opened 2022-12-13 14:55 UTC
I experience actions called two times in certain situation
I have interval website is open at a slug (action) 
Then I modify the code and that triggers a rebuild
Once rebuilt, while the frontend refreshes, and I see in BE logs that the handler for the opened view is called 2 times

I notice 2 errors in browser console when this happens
first 2 lines are last logs before I trigger rebuild
the error logs are during (re) connect
one of the handlers seem to be (attempted) to be removed twice

![image](https://user-images.githubusercontent.com/88164058/207365693-93238e15-5178-4d24-a458-c48772d7f249.png)

**Comment by jacobmischka** [comment] 2022-12-13 16:20
The error logs in the browser console are expected, it means your backend hadn't happened to reconnect yet the first time the page tried reconnecting. Those `removing handlers` logs should have been silenced, apologies, but there's nothing odd happening there (the duplicate ID isn't a problem, though it does seem odd).

I'm unable to reproduce the action starting twice on the backend: a `console.log` on the first line of the action is triggered only once upon reconnect. Could you provide some more information about the action and your setup that might help reproduce this?

Thanks!

**Comment by apopant** [comment] 2022-12-13 17:50
We use NestJS, I don't see issues in the setup, actions registered once.

I was looking at the socket data, there are plenty of log messages there...
I don't see how to extract them, don't see the same in history

here is a screenshot of the websocket log (cleared before I rebuild backend, browser is at the action page)
![image](https://user-images.githubusercontent.com/88164058/207407354-5c974325-984a-4133-a2cb-15158947abb4.png)

here is the same page on open (just selected from dashboard, no rebuilds)
![image](https://user-images.githubusercontent.com/88164058/207407552-e68aaaab-3b74-407b-a79c-70d92a040262.png)

**Comment by jacobmischka** [comment] 2022-12-14 18:53
I am able to reproduce it now, thanks! Turns out it happens in Chrome but not other browsers. Looking into a fix now.

In the meantime, can I ask what version of `@interval/sdk` you're using? Version `^0.35.0` should drop the duplicate messages so the transaction won't be started multiple times, could you try that if you aren't already?

Thanks for reporting this bug!

**Comment by jacobmischka** [comment] 2022-12-14 19:24
Er sorry about the automatic premature close. I just committed a fix for this, should be live shortly. I'll write back once it's been deployed!

**Comment by jacobmischka** [comment] 2022-12-14 22:34
It should be deployed now, please write back if you still experience the issue and we'll take another look. Thanks again for your help!

**Closed by jacobmischka** 2022-12-14 22:34 UTC
Labels: bug

**Comment by apopant** [comment] 2022-12-15 06:42
> I am able to reproduce it now, thanks! Turns out it happens in Chrome but not other browsers. Looking into a fix now.

I was using Edge

> In the meantime, can I ask what version of @interval/sdk you're using? Version ^0.35.0 should drop the duplicate messages so the transaction won't be started multiple times, could you try that if you aren't already?

Today the error didn't happen, also didn't see it in `0.35.2`

thank you!
